#cloud-config
write_files:
  - content: |
      # server config file
      datacenter="aws"
      data_dir  = "/opt/nomad/data"
      bind_addr = "0.0.0.0"
      server {
        enabled = true
        bootstrap_expect = ${bootstrap_expect}
        server_join {
          retry_join = ["${retry_join}"]
          retry_max = 5
          retry_interval = "15s"
        }
        #if OSS binary is used then the license configuration is ignored
        #license_path = "/etc/nomad.d/nomad.hclic"
      }
    permissions: '0750'
    path: /etc/nomad.hcl.cloud_init
runcmd:
  - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
  - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
  - sudo apt-get update
  - sudo apt-get install -y nomad
  - sudo cp /etc/nomad.d/nomad.hcl /etc/nomad.hcl.apt
  - sudo cp /etc/nomad.hcl.cloud_init /etc/nomad.d/nomad.hcl
  - sudo chown nomad:nomad /etc/nomad.d/nomad.hcl
  - sudo systemctl enable nomad
  - sudo systemctl stop nomad
  - sudo systemctl start nomad
packages_update: true
packages:
  - unzip
